version: '3.5'

services:
  
  medicalservice:
    container_name: MedicalService
    build: 
      context: .
      dockerfile: Medical.Web.Api/Dockerfile
    ports: 
      - "5000:80"
    environment:  
      - ConnectionStrings:DbServer=Server=mssqlserver;Database=MedicalDb;User Id=sa;Password=Adm.SqlServer;
      - Serilog:WriteTo:0:Args:databaseUrl=mongodb://admin:admin@msmongo:27017/medical?authSource=admin
    depends_on: 
      - mssqlserver
      - msmongo
    networks: 
      - netMsService

  mssqlserver:
    container_name: mssqlserver
    image: microsoft/mssql-server-linux:2017-latest
    restart: always
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "Adm.SqlServer"
        ACCEPT_EULA: "Y"
    networks: 
      - netMsService
      
  msmongo:
    container_name: msmongo
    image: mongo
    restart: always
    ports:
        - "27017:27017"
    environment:
        MONGO_INITDB_DATABASE: admin
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin
    networks: 
      - netMsService

networks: 
  netMsService:
    driver: bridge